base_url = "https://lazyeye.dev"
title = "Gabe Weiner"
author = "Gabe Weiner"
generate_feeds = true

[markdown]
smart_punctuation = true 
bottom_footnotes = true
insert_anchor_links = "heading"

[markdown.highlighting]
light_theme = "github-light"
dark_theme = "tokyo-night"
error_on_missing_language = true
data_attr_position = "pre"

[extra]
email = "imlazyeye@gmail.com"
resume = "gabe-weiner-resume.pdf"
linkedin = "https://www.linkedin.com/in/gabe-weiner"
github = "https://github.com/imlazyeye"
